### ISSUE TITLE
Inspector doesn't work properly with classic ES5 decorator syntax

### ISSUE THREAD

**Issue by vslinko** [lahmatiy/component-inspector#11]
ES6 syntax:

``` js
function decorator() {}
@decorator
export default class Component {}
```

ES5 syntax:

``` js
function decorator() {}
class Component {}
export default decorator(Component);
```

Result of using classic decorator syntax:

![Alt text](https://monosnap.com/file/6Mhv59lJwOE9PaRGnta7c6MqjPyJ8x.png)

**Comment by vslinko** [comment]
As workaround I can suggest separate those components to different levels:

```
<Connect(Testable(LocaleButtons))>
  <Testable(LocaleButtons)>
    <LocaleButtons>
    </LocaleButtons>
  </Testable(LocaleButtons)>
</Connect(Testable(LocaleButtons))>
```

**Comment by chicoxyzzy** [comment]
same issue

**Comment by chicoxyzzy** [comment]
There will be [some](https://github.com/facebook/react/pull/5190) [changes](https://github.com/facebook/react/pull/5190) in React 0.15 and it's [DevTools](https://github.com/facebook/react/issues/5306) so @vslinko let's keep an eye on these

**Comment by vslinko** [comment]
I close this issue because a lot of time has passed.
