### ISSUE TITLE
"open in editor" doesn't work on windows

### ISSUE THREAD

**Issue by anorudes** [lahmatiy/component-inspector#13]
Hello, lahmatiy, nice inspector, but i don't know how to resolve problem with "open in editor".
I can't see link.

Code: 
```
<script>window.OPEN_FILE_URL = '/open-in-editor';</script>
<script src="node_modules/component-inspector/dist/react.js"></script>
<script src="dist/bundle.js"></script>
```

Also the message "Open file in editor` is not supported" (or other messages) don't show in the console.

**Comment by lahmatiy** [comment]
Probably editor is not configured correctly.
See discussion #9 (last comments), it might help.

**Comment by anorudes** [comment]
Yes, i saw that comment and maked change, but link doesn't work. Video: https://monosnap.com/file/SLWxhzEA1JNRKkonXLcPfz7gjLBsJ2

**Comment by lahmatiy** [comment]
Ah, I see. You need setup code instrumenting, by babel plugin. See details here https://github.com/lahmatiy/component-inspector#additional-features

**Comment by anorudes** [comment]
Thanks, it is working now. But he open empty file "index.js" :)

**Comment by lahmatiy** [comment]
Is file name correct?
If yes, than problem with source path. Probably you need setup [basePath](https://github.com/restrry/babel-plugin-source-wrapper#basepath) in babel plugin.
If no, than I have no idea. Needs more details.

**Comment by anorudes** [comment]
Yep!  "basePath: myPath" helped me. I understand how this work now. Thanks! =)
