### ISSUE TITLE
Online Demo please?

### ISSUE THREAD

**Issue by winkler1** [lahmatiy/component-inspector#14]
This is a cool tool - would like to add to react.rocks to get more exposure...

**Comment by lahmatiy** [comment]
Thanks you for feedback.

Online demo with all features is not possible (at least we can't provide `open file in editor` feature). Since this tool is for developing environment, not a production.
But probably `open file in editor` feature is not so important for demo and we can build limited version or some sort of mocks.

Any suggestions for demo app? I used `redux-chat` for videos, but may be you know better app example?

**Comment by winkler1** [comment]
Hi-
 Perhaps TODOMVC? It's familiar and easy. You'd want to focus on your inspector bit, not writing a demo app :)
  I looked at https://github.com/anorudes/redux-goals -- added your inspector to the HTML. But the file sourcing wasn't hooked up properly. That might be an example too, since it looks like he's already (sort of) using your inspector.
Regards,
Jeff

**Comment by winkler1** [comment]
BTW, how I found that example usage :) - https://github.com/search?utf8=%E2%9C%93&q=component-inspector+filename:package+language:JSON&type=Code&ref=searchresults

**Comment by lapanoid** [comment]
component-inspector already contains react-todomvc as example (redux-based) https://github.com/lahmatiy/component-inspector/tree/master/examples/react-todomvc
agree with @winkler1  - no need to make example with complex app

**Comment by lahmatiy** [comment]
Done!
http://lahmatiy.github.io/component-inspector/examples/react-todomvc/

**Comment by lapanoid** [comment]
Awesome=)

**Comment by winkler1** [comment]
Whoah - great work! :+1:

**Comment by lahmatiy** [comment]
@winkler1 I submitted link to react.rocks

**Comment by lapanoid** [comment]
@lahmatiy maybe there should be some mention in demo about open in editor feature?
Something like "if you run this locally you can open corresponding code in your editor on click".
What do you think?

**Comment by lahmatiy** [comment]
@lapanoid I thought about it. Going to add it later.

**Comment by lahmatiy** [comment]
Note added. And even animated hint with instructions :)
