### ISSUE TITLE
What about babel6?

### ISSUE THREAD

**Issue by cevek** [lahmatiy/component-inspector#18]

**Comment by lahmatiy** [comment]
Sorry, but how does babel relate to component-inspector?

**Comment by cevek** [comment]
As I understand for transformation react code component-inspector use babel plugin, but this plugin is outdated.

**Comment by lahmatiy** [comment]
Component Inspectors doesn't use babel or any other things to transform your code. But you can setup something for your project to instrument your code to get information about object/function locations (see [Additional features](https://github.com/lahmatiy/component-inspector#additional-features) in readme).
For example, `babel-plugin-source-wrapper` can be used. Yep, its master is using babel 5, but it also has a [branch for babel 6](https://github.com/restrry/babel-plugin-source-wrapper/tree/babel6).
Anyway it's related to external things not to Component Inspector itself.

**Comment by lahmatiy** [comment]
I think issue can be closed since [plugin](https://github.com/restrry/babel-plugin-source-wrapper/releases/tag/v2.0.0) supports Babel 6 already. [Example](https://github.com/lahmatiy/component-inspector/tree/master/examples/react-todomvc) was switched to Babel 6 too.
