### ISSUE TITLE
Is it possible to import inspector from webpack bundle?

### ISSUE THREAD

**Issue by vslinko** [lahmatiy/component-inspector#2]
I try to import `component-inspector/dist/react` before all my other imports inside webpack entry file and I receive a strange error:

```
Module not found: Error: Cannot resolve module 'fs'
```

**Comment by lahmatiy** [comment]
You shouldn't add it to webpack entry point, as it'll be processed by webpack added to bundle (actually I don't try this scenario). Just include it in html file via `<script>` before bundle.

**Comment by vslinko** [comment]
I understand that I shouldn't but I'm just wondering about this possibility.
Reason is that I don't want to add extra `<script>` tag which references to `node_modules`.

**Comment by lahmatiy** [comment]
Well, I think about how to simplify this injection. I'm trying your scenario later, investigating issue.
Did you try exclude this file from transformation pipeline?

**Comment by vslinko** [comment]
I excluded it using `module.noParse`. Build is fixed but I get a new error:

![Alt text](https://monosnap.com/file/3M5syIRTgpuFqJoxwh2NbFqUducBFF.png)
![Alt text](https://monosnap.com/file/rNBF5JOHCDtZuD7AFVOmN0zKIrnBkw.png)

**Comment by lahmatiy** [comment]
I see, `basis.js` core could run on `node.js` environment (it uses by app builder). So it has some code for `node.js`. But `webpack` tries resolve any `require` it met.
I think problem is clear to me. Patch is coming soon.

**Comment by lahmatiy** [comment]
Fixed in 6780a75537496e081bcf135996598cc1dbac7a84
Please, use `1.0.1`

**Comment by vslinko** [comment]
Yes, now it's working, but my PR #1 doesn't included in 1.0.1. Could you check it?

**Comment by lahmatiy** [comment]
Ouch... fixed `1.0.2`

**Comment by vslinko** [comment]
Thank you.
