### ISSUE TITLE
Addition information in logInfo

### ISSUE THREAD

**Issue by tenorok** [lahmatiy/component-inspector#20]
Hello and thank you for this amazing inspector!

I try to integrate it into our project and faced with necessity to add some information into `console.log()`, which printing at: https://github.com/lahmatiy/component-inspector/blob/5ea4afc6dca8ad0f9bad24b7b1d89dae58743112/src/inspector/dom-viewer/index.js#L137-L144

Is it possible?

**Comment by tenorok** [comment]
And just one more question.
Can I add determine to templates? For example, create one more link to here: https://github.com/lahmatiy/component-inspector/blob/5ea4afc6dca8ad0f9bad24b7b1d89dae58743112/src/inspector/dom-viewer/template/window.tmpl#L12

**Comment by lahmatiy** [comment]
What sort of information you want to add? Probably we can add extra API method to customise information for `console.log()` or even override `logInfo` method logic.

> Can I add determine to templates? For example, create one more link to here:

I guess you can. But I need to know what problem are you solving. Probably will be suitable to override info panel rendering at all.
Keep in mind, that backbone and react integrations are merely examples. You can hack inspector as you want. But if you see some ways for improvements that can be halpful for others - let's extend basic functionality.

**Comment by tenorok** [comment]
In our project we using BEM and opportunity to print entering BEMJSON-tree would be helpfully. Somiteimes this tree is very big, what the reason that printing him in the component-popup is uncomfortable.

**Comment by lahmatiy** [comment]
Are you use API free build? If we add extra methods to customise console output does it solve the problem?
Another possible solution is add custom panel (with overflow) to Inspector sidebar. Are you sure it's not suitable?

**Comment by tenorok** [comment]
Yes, we use API free build.
Customizable console output will solve our problem in whole. And I think, that it would be useful for any other needs in the future.
Custom panel – interesting thing and it is can solve our problem too. But I'm afraid, that it will hard in realization and inspector may become monstrous due so bulky interface.

**Comment by lahmatiy** [comment]
Component Inspector [1.3.0](https://github.com/lahmatiy/component-inspector/releases/tag/v1.3.0) is out. It has new methods to customize logging and helpers to create custom info sections (see [Custom info sections](https://github.com/lahmatiy/component-inspector#custom-info-sections)).
I believe it meets your needs ;)

**Comment by tenorok** [comment]
Cool and so fast! Thank you :-)
