### ISSUE TITLE
Component Inspector doesn't work with React 15

### ISSUE THREAD

**Issue by karuppasamy** [lahmatiy/component-inspector#21]
I'm getting the below error after upgrading to `react 15.0.2` when mouseover on the page/component(s).

<img width="1257" alt="screen shot 2016-05-09 at 2 36 30 pm" src="https://cloud.githubusercontent.com/assets/264525/15105390/d6d25060-15f3-11e6-8f46-e6053247e833.png">

**Comment by lahmatiy** [comment]
Yep, React API is changed and it doesn't work now :(
Will try to fix it

**Comment by lahmatiy** [comment]
Component inspector [1.4](https://github.com/lahmatiy/component-inspector/releases/tag/v1.4.0) is out with React 15 support
