### ISSUE TITLE
Invalid path to file on windows platform.

### ISSUE THREAD

**Issue by Mavrin** [lahmatiy/component-inspector#25]
![image](https://cloud.githubusercontent.com/assets/1193817/15903707/a293aa8a-2db6-11e6-8b37-9ada8fc312cd.png)

Do you have any idea how we can fix it?

**Comment by Mavrin** [comment]
I found decision. I set rewrite rules for path to file.

**Comment by lahmatiy** [comment]
Could you share how rule looks?

**Comment by Mavrin** [comment]
I use `express` for server api and generating html pages and webpack devserver in develompent mode for assets.
I have next files structure and I run server from `app` folder
![image](https://cloud.githubusercontent.com/assets/1193817/16691646/156a8f2e-4536-11e6-9968-5e64f0f45cde.png)

```js
var server = new WebpackDevServer(compiler, {
    ...
    proxy: {
        '*public/js/*': {
            target: pathToTargetServer,
            rewrite: function(req) {
                req.url = req.url.replace(/.+public\//, '');
            }
        },
        '*': pathToTargetServer
    },
    publicPath: '/assets/',
    setup(app) {
        app.use(openInEditor());
    }
});
```
