### ISSUE TITLE
Any attempts at making this a chrome plugin?

### ISSUE THREAD

**Issue by DarrylD** [lahmatiy/component-inspector#26]
As a companion or addition to the [react devtools](https://github.com/facebook/react-devtoolshttps://github.com/facebook/react-devtools) plugin would be great. Wondering if any restrictions have been found?

**Comment by lahmatiy** [comment]
I'm working on it in [rempl](https://github.com/lahmatiy/component-inspector/tree/rempl) branch. Coming soon ;)

**Comment by lahmatiy** [comment]
Since 1.6 it's possible to run inspector in Chrome devtools, see [release notes](https://github.com/lahmatiy/component-inspector/releases/tag/v1.6.0)
