### ISSUE TITLE
How to make file locations visible?

### ISSUE THREAD

**Issue by vslinko** [lahmatiy/component-inspector#3]
I'm using component-inspector with react but without basis server.
As I see, transpiled source contains references to the file locations but those locations doesn't visible in the inspector popup.
I try to find a reason inside your source code but it's too hard for me and I need your help.

**Comment by vslinko** [comment]
Looks like I has conflict between plugin definitions. Now, when my babel is properly configured I get an error:
`Uncaught ReferenceError: $devinfo is not defined`

**Comment by vslinko** [comment]
Where to get `$devinfo` implementation?

**Comment by lahmatiy** [comment]
Yes, instrumented code needs for runtime API. Some version of It could be found here https://github.com/basisjs/basisjs-tools-instrumenter/blob/master/js-runtime.js
But I'm busy to make it much easily. Will be available today later (partially done already).

**Comment by lahmatiy** [comment]
I added runtime API script to `babel-plugin-source-wrapper` and implemented new option `runtime` for it. Look for updated readme for details: https://github.com/restrry/babel-plugin-source-wrapper
You can also find example for webpack config there.

**Comment by lahmatiy** [comment]
You can try it now from repo, or wait a little until I fix issue with `require.ensure` and publish new version.

**Comment by lahmatiy** [comment]
Is it ok now? Could we close issue?

**Comment by vslinko** [comment]
It works. Thank you.
