### ISSUE TITLE
Links to component class

### ISSUE THREAD

**Issue by vslinko** [lahmatiy/component-inspector#5]
Now `component-inspector` shows me only component instance location:
![Alt text](https://monosnap.com/file/jQoNCjEM0szoe5G90wqiQTGZ57Fg3V.png)

How to enable all features from this gif?
![](https://github.com/lahmatiy/component-inspector/raw/master/docs/img/intro.gif)

**Comment by lahmatiy** [comment]
Looks something changed in react and class resolving doesn't work (https://github.com/lahmatiy/component-inspector/blob/master/src/react/inspector/template-info/index.js#L73)
What is your React version?

**Comment by vslinko** [comment]
0.14.0-rc1

**Comment by lahmatiy** [comment]
Ok. I'll check it.
Also I see no code snippets in popup :(

Coming back to work on it later this week. Fixing issues as well.

**Comment by lahmatiy** [comment]
I checked on 0.14.0-rc1 – it's works as expected. If no link to class it means no meta information was attached to class.
Looks like problem with instrumenting here. Could you provide example of class definition you use?

**Comment by vslinko** [comment]
I'm using es6 classes. Also I'm using many decorators. Some of my components have 4 or 5 higher order components on them attached via decorators.

```
import React, {PropTypes} from 'react';
import testable from 'frontend/utils/testable';

@testable()
export default class SignInForm extends React.Component {
  static propTypes = {
    // ...
  }

  render() {
    return (
      <form onSubmit={handleSubmit}>
       {/* ... */}
      </form>
    );
  }
}
```

**Comment by lahmatiy** [comment]
Still works to me :-/
Could you provide instrumented version of your example?
What version of `babel` and `babel-plugin-source-wrapper`? Is `babel-plugin-source-wrapper` goes before any other plugins (except `babel-plugin-react-display-name`)?

Also you can find an universal version in `master`, as I promised. All react specifics could be found in https://github.com/lahmatiy/component-inspector/blob/master/src/api-adapter/react.js – maybe some mistake here (but I believe it's an instrumentation problem).

**Comment by vslinko** [comment]
Variant 1: Class found, render method found, problem in source code.
```js
export default class Test extends React.Component {
  render() {
    return <div>qwe</div>
  }
}
```
![Alt text](https://monosnap.com/file/W9iTfLESN2LpNTetqQuCljM3KABHur.png)

Variant 2: Found class and render method, but they are referenced to wrapped class. Problem in source code still exists.

```js
function decorator(Component) {
  return class Wrapper extends React.Component {
    render() {
      return <Component />;
    }
  }
}

@decorator
export default class Test extends React.Component {
  render() {
    return <div>qwe</div>
  }
}
```

Variant 3 (decorator from node_modules): class not found.
```js
import {connect} from 'react-redux';

@connect()
export default class Test extends React.Component {
  render() {
    return <div>qwe</div>
  }
}
```

**Comment by vslinko** [comment]
So, class not found because inspector looking for wrapped class, but wrapped class doesn't instrumented.

**Comment by vslinko** [comment]
Why source code referenced to html? I don't know.

I'm using:
```
    "component-inspector": "^1.1.0",
    "express-open-in-editor": "^1.0.0",
    "babel-plugin-source-wrapper": "^1.1.1",
```

**Comment by lahmatiy** [comment]
What about `babel` version? I know resulting code for classes was changed some versions ago.

> Why source code contains html? I don't know.
It tries get original source by request to server. Requested file is showing in popup header (`/src/long/path/to/LocaleButtonsContainer.js` on your screenshot). I suppose server response with `html` instead of original file.

I think we should find way to tell inspector to use bundle source (with its source map) if possible.

**Comment by lahmatiy** [comment]
Thank you for your helpful examples.
Variants 2 and 3 are requiring investigation and improvements. I didn't know decorators could replace class applied to for new one. Looks like a hack still :)

**Comment by vslinko** [comment]
> What about babel version?
```
    "babel": "^5.8.23",
```

> I suppose server response with html instead of original file.
Yes, you're right, it works after I configured file serving. But I don't like this.

> Looks like a hack still
It's common practice in React ecosystem. Those classes called _Higher Order Components_ like higher order functions.

**Comment by lahmatiy** [comment]
As I realised general problem is caused using decorators (HOC actually).
Problem #3 is exists because `connect` creates new class in `react-redux` and I think this code isn't instrumented. Probably only user code instrumenting now. Probably problem will gone when HOC will be processed as expected.

> Yes, you're right, it works after I configured file serving. But I don't like this.

Initial solution was designed for basis.js, where no bundle in dev mode. And module subsytem has source of any executed module, as evaluate it on fly.
But I think we could improve solution here. Some ideas:
- scan document searching for any scripts, fetch those files and build modules map if possible. Ideally move it to Web Worker (or even to Service Worker in future). But additional requests to files are still required.
- middleware for dev-server (express or whatever), that serving source fragments by request. Maybe `express-open-in-editor` may be extended, or new middleware that would provide all necessary functionality.

Second one looks better.

**Comment by vslinko** [comment]
> Probably problem will gone when HOC will be processed as expected.

Problem is gone, but there are two more issues:
1. Processing vendor code using Babel is too slow.
2. Class link is still referenced to wrapper component.

> Second one looks better.

I agree.

**Comment by lahmatiy** [comment]
> Problem is gone, but there are two more issues

It seems we have a misunderstanding. Problem with HOC is not solved yet (but just disscused with colleagues how to fix it). And when it will be fixed, it does not need to instrumenting libraries (in most cases).

> I agree.

I'm going to implement new middleware for code fragment extracting. And one more that mix two middlewares (new one and `express-open-in-editor`) to simplify setup.

**Comment by vslinko** [comment]
Great news, I'll wait.

**Comment by lahmatiy** [comment]
Mostly done on decorators. It requires new version of [babel plugin](https://github.com/restrry/babel-plugin-source-wrapper) required (not published yet). Also new custom viewer for details was implemented. Believe you like it :)

![screen shot 2015-10-06 at 02 49 04](https://cloud.githubusercontent.com/assets/270491/10296827/2bded098-6bd5-11e5-97bc-196311b55a97.png)

Some edge cases are left to fix. And I'm going to release it (and babel plugin for instrumenting). New express middlewares are coming next.

It would be great if you able to try it on your code base until release.

**Comment by vslinko** [comment]
Installed babel plugin and inspector from master branches — no decorators support.
![Alt text](https://monosnap.com/file/ocp118HFbyKtC3fa5lT55azFfedGCf.png)

BTW your screenshot is great!

**Comment by vslinko** [comment]
Looks like you forget rebuild inspector.

**Comment by lahmatiy** [comment]
You're right. Fixed.

**Comment by lahmatiy** [comment]
Just notice component name on your screenshot: `<Connect(Connect(...(SignInForm)))>`. Interesting how does it produced. I believe `<SignInForm>` should be shown. But probably with decorator support it will be ok.

**Comment by vslinko** [comment]
Basic decorator support is working:
![Alt text](https://monosnap.com/file/qRiMoRg7acw9nx6HVWGT9zgBnXtJlj.png)

Issues:
1. `render` and `class` is shifted by 1:
![Alt text](https://monosnap.com/file/63vXdv1y1TkCoRVnNGIDF4vBsRhzth.png)
First decorator shows class of component, second decorator shows class of first decorator.

2. It works with ES6 decorator syntax, but it doesn't work with classic decoration:

```
function decorator() {}
class Component {}
export default decorator(Component);
```

http://take.ms/mxJI7

**Comment by lahmatiy** [comment]
Thank you for feedback.

1. It's simple bug, will fix asap.
2. This issue is more complicated. Since there is no explicit evidences decorator is used. For static analysis it's just a function call. So I have no idea for now how to link wrapped class with class produced by "decorator" and ignore irrelevant cases :-/

**Comment by vslinko** [comment]
Is it possible to separate those components to different levels?
```
<Connect(Testable(LocaleButtons))>
  <Testable(LocaleButtons)>
    <LocaleButtons>
    </LocaleButtons>
  </Testable(LocaleButtons)>
</Connect(Testable(LocaleButtons))>
```

**Comment by vslinko** [comment]
Like React Devtools do:
![Alt text](https://monosnap.com/file/7LnXdwhde1CKAM32tz6cujbOohpvfl.png)

**Comment by lahmatiy** [comment]
> `render` and `class` is shifted by 1:

Fixed 4db0260ce720c1e0292ec3af952fcc78f55c4464

**Comment by lahmatiy** [comment]
> Is it possible to separate those components to different levels?

It's not clear to me. Do you really needs this?

```
<Connect(Testable(LocaleButtons))>
  <Testable(LocaleButtons)>
    ...
  </Testable(LocaleButtons)>
</Connect(Testable(LocaleButtons))>
```

I think it's noisy and not necessary. I want improve viewer for cases when wrapper adds extra makrup. But in simple cases virtual component is redundant.
Maybe I missed something. Could you provide more details?

**Comment by vslinko** [comment]
> Do you really needs this?

This is definitely better then `Connect(Testable(LocaleButtons)) = React.createClass`.
I suggested this as an idea how to handle classic decorators.

**Comment by lahmatiy** [comment]
Hi!
1.2 is published as is.
Can you move your suggestions to new issue? So we could close this issue since this thread has too many q/a.

**Comment by vslinko** [comment]
done

**Comment by lahmatiy** [comment]
Thank you a lot!
