### ISSUE TITLE
Provide more info about instrumeting and `$devinfo` API

### ISSUE THREAD

**Issue by filipovskii** [lahmatiy/component-inspector#6]
All information available at this moment is this:

```
$devinfo.get(obj);
// > { "loc": "app.js:..." }
```

Would be great, if the interface was fully described.

**Comment by lahmatiy** [comment]
Hm.. Actually it's not a part of inspector. Some sort of expected API could be found here: https://github.com/restrry/babel-plugin-source-wrapper/blob/master/README.md#runtime-api
But, yeah, looks like we should add description of expected API here.

**Comment by filipovskii** [comment]
mb just a link

**Comment by lahmatiy** [comment]
I believe there is should be description of expected API. And link to implementation example as well. Do you agree?

**Comment by filipovskii** [comment]
Yes, would be great
