### ISSUE TITLE
Improve description about `open file in editor` feature

### ISSUE THREAD

**Issue by filipovskii** [lahmatiy/component-inspector#7]
Current state:

> One possible way to provide this feature is some url that does the job. This url could be set via global variable `OPEN_FILE_URL`.
>
> window.OPEN_FILE_URL = '/open-in-editor';

More info and examples on how to implement this would be helpful.

**Comment by lahmatiy** [comment]
Most likely this variable could be defined by some sort of injection or source preprocessing (a.e. webpack.DefinePlugin). But I'm not sure what kind of examples would be useful. Could you advise?

**Comment by filipovskii** [comment]
I'm more talking about what's expected of this URL. When will it be called? What parameters will be passed etc

**Comment by lahmatiy** [comment]
Clarify some moment https://github.com/lahmatiy/component-inspector#opening-file-in-editor
Is it ok now?

**Comment by filipovskii** [comment]
Yes, now it's significantly better.
